config/routes.rb
DemoApp::Application.routes.draw do
  resources :biomarkers

  resources :projects

end

app/models/biomarker.rb
class Biomarker < ActiveRecord::Base
  belongs_to :project


end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :biomarkers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/biomarkers_controller.rb
class BiomarkersController < ApplicationController
  before_action :set_biomarker, only: [:show, :edit, :update, :destroy]

  # GET /biomarkers
  # GET /biomarkers.json
  def index
    @biomarkers = Biomarker.all
  end

  # GET /biomarkers/1
  # GET /biomarkers/1.json
  def show
  end

  # GET /biomarkers/new
  def new
    @biomarker = Biomarker.new
  end

  # GET /biomarkers/1/edit
  def edit
  end

  # POST /biomarkers
  # POST /biomarkers.json
  def create
    @biomarker = Biomarker.new(biomarker_params)

    respond_to do |format|
      if @biomarker.save
        format.html { redirect_to @biomarker, notice: 'Biomarker was successfully created.' }
        format.json { render action: 'show', status: :created, location: @biomarker }
      else
        format.html { render action: 'new' }
        format.json { render json: @biomarker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /biomarkers/1
  # PATCH/PUT /biomarkers/1.json
  def update
    respond_to do |format|
      if @biomarker.update(biomarker_params)
        format.html { redirect_to @biomarker, notice: 'Biomarker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @biomarker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /biomarkers/1
  # DELETE /biomarkers/1.json
  def destroy
    @biomarker.destroy
    respond_to do |format|
      format.html { redirect_to biomarkers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_biomarker
      @biomarker = Biomarker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def biomarker_params
      params.require(:biomarker).permit(:marker, :matrix, :purpose, :decision, :evidence_level, :analyte_type, :clinical_relevance, :project_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :code, :area, :stage, :tmcp_rep, :bm_rep, :priority, :fih_target)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/biomarkers_helper.rb
module BiomarkersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/biomarkers/_form.html.erb
<%= form_for(@biomarker) do |f| %>
  <% if @biomarker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@biomarker.errors.count, "error") %> prohibited this biomarker from being saved:</h2>

      <ul>
      <% @biomarker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :marker %><br>
    <%= f.text_field :marker %>
  </div>
  <div class="field">
    <%= f.label :matrix %><br>
    <%= f.text_field :matrix %>
  </div>
  <div class="field">
    <%= f.label :purpose %><br>
    <%= f.text_field :purpose %>
  </div>
  <div class="field">
    <%= f.label :decision %><br>
    <%= f.text_field :decision %>
  </div>
  <div class="field">
    <%= f.label :evidence_level %><br>
    <%= f.text_field :evidence_level %>
  </div>
  <div class="field">
    <%= f.label :analyte_type %><br>
    <%= f.text_field :analyte_type %>
  </div>
  <div class="field">
    <%= f.label :clinical_relevance %><br>
    <%= f.text_field :clinical_relevance %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.number_field :project_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/biomarkers/edit.html.erb
<h1>Editing biomarker</h1>

<%= render 'form' %>

<%= link_to 'Show', @biomarker %> |
<%= link_to 'Back', biomarkers_path %>

app/views/biomarkers/index.html.erb
<h1>Listing biomarkers</h1>

<table>
  <thead>
    <tr>
      <th>Marker</th>
      <th>Matrix</th>
      <th>Purpose</th>
      <th>Decision</th>
      <th>Evidence level</th>
      <th>Analyte type</th>
      <th>Clinical relevance</th>
      <th>Project</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @biomarkers.each do |biomarker| %>
      <tr>
        <td><%= biomarker.marker %></td>
        <td><%= biomarker.matrix %></td>
        <td><%= biomarker.purpose %></td>
        <td><%= biomarker.decision %></td>
        <td><%= biomarker.evidence_level %></td>
        <td><%= biomarker.analyte_type %></td>
        <td><%= biomarker.clinical_relevance %></td>
        <td><%= biomarker.project_id %></td>
        <td><%= link_to 'Show', biomarker %></td>
        <td><%= link_to 'Edit', edit_biomarker_path(biomarker) %></td>
        <td><%= link_to 'Destroy', biomarker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Biomarker', new_biomarker_path %>

app/views/biomarkers/new.html.erb
<h1>New biomarker</h1>

<%= render 'form' %>

<%= link_to 'Back', biomarkers_path %>

app/views/biomarkers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Marker:</strong>
  <%= @biomarker.marker %>
</p>

<p>
  <strong>Matrix:</strong>
  <%= @biomarker.matrix %>
</p>

<p>
  <strong>Purpose:</strong>
  <%= @biomarker.purpose %>
</p>

<p>
  <strong>Decision:</strong>
  <%= @biomarker.decision %>
</p>

<p>
  <strong>Evidence level:</strong>
  <%= @biomarker.evidence_level %>
</p>

<p>
  <strong>Analyte type:</strong>
  <%= @biomarker.analyte_type %>
</p>

<p>
  <strong>Clinical relevance:</strong>
  <%= @biomarker.clinical_relevance %>
</p>

<p>
  <strong>Project:</strong>
  <%= @biomarker.project_id %>
</p>

<%= link_to 'Edit', edit_biomarker_path(@biomarker) %> |
<%= link_to 'Back', biomarkers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :area %><br>
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :stage %><br>
    <%= f.text_field :stage %>
  </div>
  <div class="field">
    <%= f.label :tmcp_rep %><br>
    <%= f.text_field :tmcp_rep %>
  </div>
  <div class="field">
    <%= f.label :bm_rep %><br>
    <%= f.text_field :bm_rep %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.text_field :priority %>
  </div>
  <div class="field">
    <%= f.label :fih_target %><br>
    <%= f.text_field :fih_target %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Area</th>
      <th>Stage</th>
      <th>Tmcp rep</th>
      <th>Bm rep</th>
      <th>Priority</th>
      <th>Fih target</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.code %></td>
        <td><%= project.area %></td>
        <td><%= project.stage %></td>
        <td><%= project.tmcp_rep %></td>
        <td><%= project.bm_rep %></td>
        <td><%= project.priority %></td>
        <td><%= project.fih_target %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @project.code %>
</p>

<p>
  <strong>Area:</strong>
  <%= @project.area %>
</p>

<p>
  <strong>Stage:</strong>
  <%= @project.stage %>
</p>

<p>
  <strong>Tmcp rep:</strong>
  <%= @project.tmcp_rep %>
</p>

<p>
  <strong>Bm rep:</strong>
  <%= @project.bm_rep %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @project.priority %>
</p>

<p>
  <strong>Fih target:</strong>
  <%= @project.fih_target %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>